# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: pc.501.hellometer.openvpn.com
  become: yes

  tasks:

# - name: Call Roles
#   hosts: servers
#   ansible.builtin.shell: sudo reboot


- name: Reboot servers
  hosts: servers
  become: yes
  tasks:
    - name: Reboot the servers
      ansible.builtin.shell: sudo reboot
